### ISSUE TITLE
External does not use the module directory as the current working directory

### ISSUE THREAD

**Issue by ramarnat** [hashicorp/terraform-provider-external#10]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.11.1

### Affected Resource(s)
+ provider.external v1.0.0

### Expected Behavior
The external data resource should run inside the module directory

### Actual Behavior
runs where the terraform plan is run

### References
Can probably be fixed by https://github.com/grv87/terraform/commit/569eef0fd111e06b25e89104c89d187303e65f63 but seems to have been lost since march

**Comment by grv87** [comment]
That commit was merged as #12. But still not released.
That would give the option to set working directory by hand. But I think this is only workaround for this issue.

**Comment by GroovyCarrot** [comment]
Would it be possible to get a release out for `working_dir` support?

**Comment by kmoe** [comment]
#12 was released in v1.1.0.
