### ISSUE TITLE
The terraform-provider-external_v2.2.0_x5 plugin crashed!

### ISSUE THREAD

**Issue by petrmvala** [hashicorp/terraform-provider-external#110]
### Terraform CLI and Provider Versions

terraform v1.1
hashicorp/external v2.2.0

### Terraform Configuration

```terraform
terraform {
  required_providers {
    acme = {
      source = "vancluever/acme"
    }
    aws = {
      source = "hashicorp/aws"
    }
    cloudflare = {
      source = "cloudflare/cloudflare"
    }
    datadog = {
      source = "datadog/datadog"
    }
    external = {
      source = "hashicorp/external"
    }
    gitlab = {
      source = "gitlabhq/gitlab"
    }
    google = {
      source = "hashicorp/google"
    }
    null = {
      source = "hashicorp/null"
    }
    random = {
      source = "hashicorp/random"
    }
    tls = {
      source = "hashicorp/tls"
    }
    vault = {
      source = "hashicorp/vault"
    }
  }
  required_version = ">= 0.14"
  experiments = [module_variable_optional_attrs]
}
terraform {
  backend "gcs" {
    bucket = "tf_state_gcp_projects_prod"
  }
  required_version = ">= 0.13"
}
```

### Expected Behavior

No errors

### Actual Behavior

│ Error: Plugin did not respond
│ 
│   with module.kiwibase_develop.data.external.codeowners,
│   on gcp_project/gitlab_protect.tf line 43, in data "external" "codeowners":
│   43: data "external" "codeowners" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ReadDataSource call. The plugin logs may contain
│ more details.
╵
╷
│ Error: Request cancelled
│ 
│   with module.booking_production.data.external.codeowners,
│   on gcp_project/gitlab_protect.tf line 43, in data "external" "codeowners":
│   43: data "external" "codeowners" {
│ 
│ The plugin.(*GRPCProvider).ValidateDataResourceConfig request was
│ cancelled.
╵
Stack trace from the terraform-provider-external_v2.2.0_x5 plugin:
panic: interface conversion: interface {} is nil, not string
goroutine 26 [running]:
github.com/terraform-providers/terraform-provider-external/internal/provider.dataSourceRead(0xd35b68, 0xc0003871a0, 0xc0001ffa00, 0x0, 0x0, 0xc00028cce0, 0xc00029b8b8, 0x40e0f8)
	github.com/terraform-providers/terraform-provider-external/internal/provider/data_source.go:88 +0x1b66
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000158380, 0xd35af8, 0xc000153140, 0xc0001ffa00, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:358 +0x17f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ReadDataApply(0xc000158380, 0xd35af8, 0xc000153140, 0xc0001ff900, 0x0, 0x0, 0x0, 0xc0001ff900, 0x0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:569 +0xfd
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadDataSource(0xc000138768, 0xd35af8, 0xc000153140, 0xc00075c4a0, 0xc53093, 0x12, 0x0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:1133 +0x518
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadDataSource(0xc0001fe500, 0xd35ba0, 0xc000153140, 0xc00019ca00, 0x0, 0x0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:478 +0x2f5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadDataSource_Handler(0xc1b500, 0xc0001fe500, 0xd35ba0, 0xc000282060, 0xc000386d20, 0x0, 0xd35ba0, 0xc000282060, 0xc000286000, 0xa1)
	github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:416 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00016e540, 0xd3c778, 0xc000582c00, 0xc000370100, 0xc000447140, 0x11429b0, 0x0, 0x0, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc00016e540, 0xd3c778, 0xc000582c00, 0xc000370100, 0x0)
	google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000042220, 0xc00016e540, 0xd3c778, 0xc000582c00, 0xc000370100)
	google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd
Error: The terraform-provider-external_v2.2.0_x5 plugin crashed!

### Steps to Reproduce

1. `terraform plan`

### How much impact is this issue causing?

Medium

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by petrmvala** [comment]
Is this project dead?

**Comment by mickvav** [comment]
Hi, @petrmvala .
Disclaimer - I am not related to this particular project, just looking around as want-to-be user, so do not take my opinion as developers answer.

What I see from your snippet of code is that you use version statement on global level and you do not actually provide details of what code you are trying to execute under the hood - are you sure that it actually works and returns correct json?

You may run your terraform under strace to see what actually happens there.

**Comment by mickvav** [comment]
That is actually important clarification - this thing actually works well with small jsons, at least - for me. So probably there is some size of json that breaks it? As you have the setup at hand, may be you can bisect to it?
(e.g. 100 - breaks, 50 - breaks, 25 - works, 37 - breaks ...) Once done, we can look closer into json-reading code - it is either file read buffer or some postprocessing.

**Comment by petrmvala** [comment]
Ah, I found out the problem!

This was how I called it:

```
data "external" "codeowners" {
  program = [
    "${path.module}/codeowners_present.sh",
    var.gitlab_project,
    local.gitlab_protect_default_group
  ]
}
```

The reason it did not fail on me was that I always tried it on a gitlab repository. But in the pipeline it is running on a lot of projects and some of them do not have a gitlab repository, therefore the `var.gitlab_project = ""`. That is why it fails on https://github.com/hashicorp/terraform-provider-external/blob/main/internal/provider/data_source.go#L88 with `panic: interface conversion: interface {} is nil, not string`

**Comment by bflad** [comment]
Hi @petrmvala and @mickvav 👋  Thank you for discussing this and thank you very much for finding the root cause!

This certainly was a code issue in the data source, which was reproducible by using a test configuration containing `program` arguments of `""` (solely or intermixed). To that end, I have submitted https://github.com/hashicorp/terraform-provider-external/pull/119, which will omit those missing elements from the program execution rather than a panic. In the case of all empty string elements, such as a single element that is a variable that evaluates to `""`,  it will also return a specialized error diagnostic rather than a panic.

**Comment by petrmvala** [comment]
Thank you @bflad !
