### ISSUE TITLE
Returned keys containing a "." create a nested map instead of keeping the "."

### ISSUE THREAD

**Issue by ddelbondio** [hashicorp/terraform-provider-external#18]
### Terraform Version#
    Terraform v0.11.7
    + provider.external v1.0.0
    + provider.null v1.0.0

### Affected Resource(s)
External data provider
### Terraform Configuration Files
```hcl
data external ext {
  program = ["echo", "{\"foo.bar\": \"value\"}"]
}

resource "null_resource" "test" {
  triggers {
    foo = "${format("%v", data.external.ext.result)}"
  }
}

```

### Debug Output
Does not contain anything useful related to the issue. I can provide it if needed.

### Expected Behavior
`data.external.ext.result` should contain a flat map: {"foo.bar": "value"}. 

### Actual Behavior
The result of the external is converted into a nested map, where the keys are split at ".".

    + null_resource.test
        id:           <computed>
        triggers.%:   "1"
        triggers.foo: "map[foo:{Variable (TypeMap): map[bar:{Variable (TypeString): value}]}]"

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

If this is intended behaviour, please regard this as a documentation bug, since I could not find any explanation of this behaviour in the docs.

**Comment by bflad** [comment]
Hi folks 👋 

A lot has changed with the Terraform configuration handling and type systems since this issue was introduced. Using the following configuration on recent versions of Terraform CLI and providers, it appears that Terraform is doing the right thing nowadays:

```terraform
terraform {
  required_version = "1.1.0"
  required_providers {
    external = {
      source  = "hashicorp/external"
      version = "2.1.0"
    }
    null = {
      source  = "hashicorp/null"
      version = "3.1.0"
    }
  }
}

data "external" "test" {
  program = ["echo", "{\"foo.bar\": \"value\"}"]
}

resource "null_resource" "test" {
  triggers = {
    foo = format("%v", data.external.test.result)
  }
}
```

```console
$ terraform init
...
$ terraform apply

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # null_resource.test will be created
  + resource "null_resource" "test" {
      + id       = (known after apply)
      + triggers = {
          + "foo" = jsonencode(
                {
                  + foo.bar = "value"
                }
            )
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

null_resource.test: Creating...
null_resource.test: Creation complete after 0s [id=8557106263948083010]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
$ terraform state show null_resource.test
# null_resource.test:
resource "null_resource" "test" {
    id       = "8557106263948083010"
    triggers = {
        "foo" = jsonencode(
            {
                foo.bar = "value"
            }
        )
    }
}
```

If there are still lingering problems on recent versions of CLI and providers, please create a new issue and we can triage further. Thank you!
