### ISSUE TITLE
darwin_arm64 external provider fails 

### ISSUE THREAD

**Issue by chukynax** [hashicorp/terraform-provider-external#241]
### Terraform CLI and Provider Versions

Terraform v1.4.6
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v5.6.2
+ provider registry.terraform.io/hashicorp/external v2.3.1
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/random v3.5.1

Your version of Terraform is out of date! The latest version
is 1.5.2. You can update by downloading from https://www.terraform.io/downloads.html

### Terraform Configuration

```terraform
data "external" "token" {
  program = ["bash", "../bitbucket_token.sh"]
}

output "name" {
  value = data.external.token
}
```

```bash
#!/bin/bash
set -e

token=$(curl -s -X POST -u "token" https://bitbucket.org/site/oauth2/access_token -d grant_type=client_credentials | jq --raw-output ".access_token")

jq -n --arg token "$token" '{"token":$token}'
```

### Expected Behavior

Can get 

data.external.token.result.token 

which is working from linux amd64

### Actual Behavior
```code
Plan: 2 to add, 1 to change, 3 to destroy.
╷
│ Error: Unexpected External Program Results
│
│   with module.amplify.data.external.token,
│   on amplify/main.tf line 2, in data "external" "token":
│    2:   program = ["bash", "../bitbucket_token.sh"]
│
│ The data source received unexpected results after executing the program.
│
│ Program output must be a JSON encoded map of string keys and string values.
│
│ If the error is unclear, the output can be viewed by enabling Terraform's logging at TRACE level. Terraform documentation on logging: https://www.terraform.io/internals/debugging
│
│ Program: /usr/bin/bash
│ Result Error: json: cannot unmarshal string into Go value of type map[string]string
```
### Steps to Reproduce

1. `terraform apply`

### How much impact is this issue causing?

High

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by austinvalle** [comment]
Hi there @chukynax 👋🏻, thanks for reporting this issue and sorry you're running into problems here.

I'm not able to replicate your issue with the same TF version/arch with this simplified example:

#### main.tf
```tf
data "external" "token" {
  program = ["bash", "./test.sh"]
}

output "name" {
  value = data.external.token
}
```
#### test.sh
```sh
#!/bin/bash
set -e

token=$(cat test.json | jq --raw-output ".access_token")

jq -n --arg token "$token" '{"token":$token}'
```
#### test.json
```json
{
    "access_token": "fake_token_123"
}
```
#### Output
```
 $ terraform plan               
data.external.token: Reading...
data.external.token: Read complete after 0s [id=-]

Changes to Outputs:
  + name = {
      + id          = "-"
      + program     = [
          + "bash",
          + "./test.sh",
        ]
      + query       = null
      + result      = {
          + token = "fake_token_123"
        }
      + working_dir = null
    }
```

I'd recommend checking the output from `$(curl -s -X POST -u "token" https://bitbucket.org/site/oauth2/access_token -d grant_type=client_credentials | jq --raw-output ".access_token")` on the `darwin_arm64` machine to ensure valid JSON is being returned.

If you're able to simplify and recreate your error, please let me know and I'll give it another try!

**Comment by chukynax** [comment]
I dont understand why but it started working ( 

sorry for disturb
