### ISSUE TITLE
Provide method to hide sensitive query data in Diffs

### ISSUE THREAD

**Issue by WilliamABradley** [hashicorp/terraform-provider-external#44]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

```
Terraform v0.13.1
```

### Affected Resource(s)
Please list the resources as a list, for example:
- data.external

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files

This will show the API key in the diff, which is undesirable.

```hcl
data "external" "submit_complex_process" {
  query = {
    API_KEY = var.API_KEY
  }
}
```

A Potential fix:
```hcl
data "external" "submit_complex_process" {
  sensitive_query = {
    API_KEY = var.API_KEY
  }
}
```

or:

```hcl
data "external" "submit_complex_process" {
  query = {
    API_KEY = var.API_KEY
  }
  sensitive_keys = ["API_KEY"]
}
```

**Comment by windsource** [comment]
I also ran into the problem that a private ssh key was logged which was a parameter to data.external. So I would appreciate if this could be implemented.

**Comment by marshallford** [comment]
I don't think the release of [0.15.0](https://github.com/hashicorp/terraform/releases/tag/v0.15.0) makes the proposed PR any simpler but it does indicate that the Hashi team has a continued vested interest in providing the right knobs to twist for marking values as sensitive. I hope that the interest extends to this ask 😄

**Comment by bflad** [comment]
Hi folks 👋  Terraform CLI versions 0.15 and later implement generic sensitive value handling that solves this problem at the Terraform configuration level, outside of any provider changes.

For example:

- Input variables can be configured with `sensitive = true`, see also: https://www.terraform.io/language/values/variables#suppressing-values-in-cli-output
- Output variables can be configured with `sensitive = true`, see also: https://www.terraform.io/language/values/outputs#sensitive-suppressing-values-in-cli-output
- Values can be marked as sensitive with the `sensitive()` function, see also: https://www.terraform.io/language/functions/sensitive

To show this in practice, check out this Terraform configuration:

```terraform
terraform {
  required_providers {
    external = {
      source  = "hashicorp/external"
      version = "2.1.1"
    }
    random = {
      source  = "hashicorp/random"
      version = "3.1.0"
    }
  }

  required_version = ">= 0.15.0"
}

variable "nonsensitive" {
  default = "nonsensitive-variable-value"
  type    = string
}

variable "sensitive" {
  default   = "sensitive-variable-value"
  sensitive = true
  type      = string
}

locals {
  converted_var = sensitive(var.nonsensitive)
  nonsensitive  = "nonsensitive-local-value"
  sensitive     = sensitive("sensitive-local-value")
}

# Example resource to forcibly show external data source plan
resource "random_pet" "test" {}

data "external" "test" {
  # Forcibly show data source plan. This is not a typical pattern.
  depends_on = [random_pet.test]

  program = ["jq", "."]
  query = {
    "nonsensitive_local"         = local.nonsensitive
    "nonsensitive_var"           = var.nonsensitive
    "sensitive_inline"           = sensitive(var.nonsensitive)
    "sensitive_local_conversion" = local.converted_var
    "sensitive_local"            = local.sensitive
    "sensitive_var"              = var.sensitive
  }
}
```

When applied, any sensitive values are not shown in the plan:

```console
$ terraform apply

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create
 <= read (data resources)

Terraform will perform the following actions:

  # data.external.test will be read during apply
  # (config refers to values not yet known)
 <= data "external" "test"  {
      + id      = (known after apply)
      + program = [
          + "jq",
          + ".",
        ]
      + query   = {
          + "nonsensitive_local"         = "nonsensitive-local-value"
          + "nonsensitive_var"           = "nonsensitive-variable-value"
          + "sensitive_inline"           = (sensitive)
          + "sensitive_local"            = (sensitive)
          + "sensitive_local_conversion" = (sensitive)
          + "sensitive_var"              = (sensitive)
        }
      + result  = (known after apply)
    }

  # random_pet.test will be created
  + resource "random_pet" "test" {
      + id        = (known after apply)
      + length    = 2
      + separator = "-"
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

Since this sensitive value handling at the Terraform configuration level should cover most use cases, I'm going to close this.

**Comment by drarko** [comment]
Hi @bflad 

It isn't clear to me case when result of external data source is a sensitive value.

How can I hide it?

**Comment by bflad** [comment]
Hi @drarko 👋  The same functionality can be used with the results:

* Output variables can be configured with sensitive = true, see also: https://www.terraform.io/language/values/outputs#sensitive-suppressing-values-in-cli-output
* Values can be marked as sensitive with the sensitive() function, see also: https://www.terraform.io/language/functions/sensitive

Wrapping the `result` attribute with the `sensitive()` function will hide the value from plan output, e.g. any of these potential usages.

```terraform
data "external" "example" {
  # ...
}

locals {
  sensitive_local = sensitive(data.external.example.result)
}

resource "example_thing" "sensitive_input" {
  some_attribute = sensitive(data.external.example.result) 
}

output "sensitive_output" {
  sensitive = true
  value      = sensitive(data.external.example.result)
}
```

If you have further configuration or troubleshooting questions, please also check out [HashiCorp Discuss](https://discuss.hashicorp.com/) where there are far more folks watching these types of topics and able to answer. The issues in this repository are only monitored by a small subset of provider maintainers for bug reports and feature requests.
