### ISSUE TITLE
Can you please create a new tag/release to include the commit fb6d7fac5d73bccb1d7aba82ba40cc2cc2719307

### ISSUE THREAD

**Issue by achinthagunasekara** [hashicorp/terraform-provider-external#48]
Hi there,

Can you please create a new tag/release to include the commit fb6d7fac5d73bccb1d7aba82ba40cc2cc2719307

We build from upstream using tags and would like to get the fix in above commit.

Many thanks

### References
https://github.com/hashicorp/terraform-provider-external/pull/46

**Comment by paultyng** [comment]
This is in v2.0.0
