### ISSUE TITLE
data external can't run program "python"

### ISSUE THREAD

**Issue by vineet-cactus** [hashicorp/terraform-provider-external#51]
Terraform version: 
- Terraform v0.11.14
- provider.aws v2.33.0
- provider.external v1.2.0

Error: can't find external program "python"

when reproducing below module, receiving above error.
https://registry.terraform.io/providers/hashicorp/external/latest/docs/data-sources/data_source#example-usage

**Comment by Sean12697** [comment]
Is `python` a valid command on the system/image you are running Terraform on> Does `python -V` return a version, if not, does `python3 -V` work?

**Comment by bflad** [comment]
Hi @vineet-cactus 👋  Thank you for raising this. The question asked above by @Sean12697 is valid in this case, but without additional information, we cannot triage this issue further and I'm going to close it. You'll need to ensure that the `python` file is available on the `PATH` and executable.

If you have further configuration or troubleshooting questions, please also check out [HashiCorp Discuss](https://discuss.hashicorp.com/) where there are far more folks watching these types of topics and able to answer. The issues in this repository are only monitored by a small subset of provider maintainers for bug reports and feature requests.
